catalog
catalogKeyClassesAndExample
	"Returns a paragraph or more describing the key classes of your project. You can use Pillar/Pier syntax to layout out the text i.e., ==Code== and - for bullet."
	^ 'Orion is too complex to be explained in these few lines. But to play with it, first create a Moose model (or import it), in the moose panel, do a right click and do Orion > Convert to ORModel. Now, open the Orion panel: you can create a child model and begin to create, delete, modify the entities.'